import { useEffect, useRef, useState } from 'react'
import { AvatarScene } from './components/AvatarScene'
import { ExperienceSettings } from './components/ExperienceSettings'
import { InteractionLab } from './components/InteractionLab'
import { MiniGame } from './components/MiniGame'
import { companion, companionBus } from './lib/companionBus'
import { resolveCompanionEvent, type CompanionEvent } from './lib/companionOrchestrator'
import { defaultCompanionSettings, type CompanionSettings } from './lib/companionSettings'
import { createGuidance, type GuidanceRequest } from './lib/guidance'
import { interactionDurations, interactionMessages, type CompanionInteraction } from './lib/interactions'
import type { CompanionState, Outfit } from './lib/types'

const stateText: Record<CompanionState, { title: string; body: string }> = {
  idle: { title: "I'm here to help", body: 'Click me or test one of the scenarios.' },
  loading: { title: 'Getting your requests ready…', body: 'Your HelpNest assistant is checking the latest information.' },
  success: { title: 'All done!', body: 'Your requests are ready.' },
  error: { title: 'Something went wrong', body: 'The request failed. You can retry or keep playing.' },
  offline: { title: "I couldn't reach assyst", body: "I'm checking the connection and will keep trying." },
  game: { title: 'HelpNest Quest', body: 'Catch requests while you wait.' },
}
const companionText: Record<CompanionState, string> = { idle:'Need anything?',loading:"I'm working on it…",success:'All done! 🎉',error:'Hmm… let me help.',offline:'Checking the connection…',game:'Have fun! 🎮' }
const demoGuidance: GuidanceRequest[] = [
  createGuidance({id:'approval-1001',type:'approval',title:'Laptop Replacement',message:'This request is awaiting your approval.',targetId:'approval-laptop',actionLabel:'Review now',priority:'urgent'}),
  createGuidance({id:'info-1002',type:'information-required',title:'VPN Access',message:'Support needs more information from you.',targetId:'info-vpn',actionLabel:'Add information',priority:'important'}),
]
const SETTINGS_KEY='helpnest-companion-settings'
function loadSettings():CompanionSettings{try{const saved=window.localStorage.getItem(SETTINGS_KEY);return saved?{...defaultCompanionSettings,...JSON.parse(saved)}:defaultCompanionSettings}catch{return defaultCompanionSettings}}

export default function App(){
  const [state,setState]=useState<CompanionState>('idle'); const [outfit,setOutfit]=useState<Outfit>('default'); const [message,setMessage]=useState(''); const [longWait,setLongWait]=useState(false); const [requestComplete,setRequestComplete]=useState(false); const [pendingOutcome,setPendingOutcome]=useState<CompanionState>('success'); const [guidance,setGuidance]=useState<GuidanceRequest|null>(null); const [settings,setSettings]=useState<CompanionSettings>(loadSettings); const [settingsOpen,setSettingsOpen]=useState(false); const [interaction,setInteraction]=useState<CompanionInteraction>('none')
  const stateRef=useRef<CompanionState>('idle'); const requestTimer=useRef<number|null>(null); const longWaitTimer=useRef<number|null>(null); const progressTimer=useRef<number|null>(null); const guideTimer=useRef<number|null>(null); const interactionTimer=useRef<number|null>(null)
  useEffect(()=>{stateRef.current=state},[state]); useEffect(()=>{window.localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings))},[settings])
  const clearSimulationTimers=()=>{[requestTimer,longWaitTimer,progressTimer].forEach(r=>{if(r.current)window.clearTimeout(r.current);r.current=null})}
  const clearInteraction=()=>{if(interactionTimer.current)window.clearTimeout(interactionTimer.current);interactionTimer.current=null;setInteraction('none')}
  const triggerInteraction=(next:CompanionInteraction,force=false)=>{if(!settings.enabled)return;if(!force&&!settings.allowInteraction)return;if(interactionTimer.current)window.clearTimeout(interactionTimer.current);interactionTimer.current=null;setState('idle');setInteraction(next);setMessage(interactionMessages[next]);if(!force){const duration=interactionDurations[next];if(duration>0)interactionTimer.current=window.setTimeout(()=>{setInteraction('none');setMessage('')},duration)}}
  const applyEvent=(event:CompanionEvent)=>{if(!settings.enabled)return;const d=resolveCompanionEvent(event);if(interactionTimer.current)window.clearTimeout(interactionTimer.current);interactionTimer.current=null;setState(d.state);setInteraction(d.interaction);setMessage(d.message)}
  useEffect(()=>companionBus.subscribe(event=>applyEvent(event)),[settings.enabled])
  const dismissGuidance=()=>{if(guideTimer.current)window.clearTimeout(guideTimer.current);guideTimer.current=null;setGuidance(null);setMessage('')}
  const guideTo=(request:GuidanceRequest)=>{if(!settings.enabled)return;clearInteraction();if(guideTimer.current)window.clearTimeout(guideTimer.current);setGuidance(request);companionBus.publish({type:'attention-required',kind:request.type==='approval'?'approval':'information',title:request.title});guideTimer.current=window.setTimeout(dismissGuidance,request.autoDismissMs??6500)}
  const simulate=(ms:number,outcome:CompanionState='success')=>{clearSimulationTimers();clearInteraction();dismissGuidance();setPendingOutcome(outcome);setRequestComplete(false);setLongWait(false);if(settings.enabled&&settings.showDuringLoading&&ms>=settings.minimumWaitMs)companion.operationStarted(ms);else setState('idle');if(ms>1800)progressTimer.current=window.setTimeout(()=>companion.operationTyping(),Math.min(2200,Math.max(900,ms*.35)));if(settings.enableMiniGames)longWaitTimer.current=window.setTimeout(()=>setLongWait(true),settings.miniGameDelayMs);requestTimer.current=window.setTimeout(()=>{setRequestComplete(true);setLongWait(false);if(stateRef.current!=='game'){if(outcome==='success')companion.operationSucceeded();else if((outcome==='error'||outcome==='offline')&&settings.showOnErrors){if(outcome==='offline')companion.operationOffline();else companion.operationFailed()}else setState('idle')}},ms)}
  const finishGame=()=>{setRequestComplete(false);if(pendingOutcome==='success')companion.operationSucceeded();else if(settings.showOnErrors){if(pendingOutcome==='offline')companion.operationOffline();else companion.operationFailed()}else setState('idle')}
  const closeGame=()=>{if(requestComplete)finishGame();else if(settings.showDuringLoading)companion.operationTyping();else setState('idle')}
  const handleGuidanceAction=()=>{const active=guidance;if(!active)return;dismissGuidance();companion.attentionCompleted(active.title);const target=document.getElementById(active.targetId);target?.scrollIntoView({behavior:'smooth',block:'center'});target?.classList.add('actionPulse');window.setTimeout(()=>target?.classList.remove('actionPulse'),1600)}
  useEffect(()=>()=>{clearSimulationTimers();if(guideTimer.current)window.clearTimeout(guideTimer.current);if(interactionTimer.current)window.clearTimeout(interactionTimer.current)},[])
  useEffect(()=>{if(!message||guidance||interaction!=='none')return;const id=window.setTimeout(()=>setMessage(''),1800);return()=>clearTimeout(id)},[message,guidance,interaction])
  const companionVisible=settings.enabled; const overlayVisible=state!=='idle'&&(state==='success'||state==='game'||(state==='loading'&&settings.showDuringLoading)||((state==='error'||state==='offline')&&settings.showOnErrors))
  return <div className={`appShell personality-${settings.personality}`}>
    <aside className="sidebar"><div className="brand">⬢ <span>HelpNest</span></div><div className="navList">{['Home','Services','My Requests','Approvals','Knowledge','Reports'].map((x,i)=><div className={'nav '+(i===0?'active':'')} key={x}>{x}</div>)}<div className="nav" onClick={()=>setSettingsOpen(true)}>Settings</div></div>{companionVisible&&<div className={`sidebarCompanion${guidance?' guideHome':''}`}><div className="sidebarBubble">{message||companionText[state]}<span className="sidebarBubbleTail"/></div><div className="sidebarAvatar"><AvatarScene state={state} outfit={outfit} interaction={interaction} onPoke={settings.allowInteraction?()=>triggerInteraction('wave'):undefined}/></div></div>}</aside>
    <main><header><input placeholder="Search for a service, request or answer…"/><div>🔔 &nbsp; Anwar ▾</div></header><section className="hero"><div><h1>Good morning, Anwar</h1><p>How can we help you today?</p></div><div className="cards"><div>🖥️<b>Report an Issue</b><span>Get help with a problem</span></div><div>🛒<b>Request Something</b><span>Browse the service catalog</span></div><div>📋<b>My Requests</b><span>Track your submissions</span></div></div><div className={`attention${guidance?' guideTarget':''}`}><b>Things needing your attention</b><div id="approval-laptop" className={`approvalRow${guidance?.targetId==='approval-laptop'?' activeGuideRow':''}`}>Laptop Replacement <span>Awaiting your approval</span><button onClick={()=>guideTo(demoGuidance[0])}>Review</button></div><div id="info-vpn" className={guidance?.targetId==='info-vpn'?'activeGuideRow':''}>VPN Access <span>Information required</span><button onClick={()=>guideTo(demoGuidance[1])}>View</button></div></div></section>
      <section className="lab"><div className="labCard"><h3>MVP controls</h3><button onClick={()=>simulate(800)}>Fast load</button><button onClick={()=>simulate(12000)}>Slow load</button><button onClick={()=>simulate(2500,'error')}>Error</button><button onClick={()=>simulate(2500,'offline')}>Offline</button><button onClick={()=>guideTo(demoGuidance[0])}>Guide me</button><button onClick={()=>companion.newUpdate('VPN Access')}>New update</button><button onClick={()=>setSettingsOpen(true)}>Experience settings</button><button onClick={()=>{clearSimulationTimers();clearInteraction();dismissGuidance();setRequestComplete(false);setState('idle')}}>Reset</button></div><div className="labCard"><h3>Avatar outfit</h3><select value={outfit} onChange={e=>setOutfit(e.target.value as Outfit)}><option value="default">Default HelpNest</option><option value="saudi-red">Saudi — red shemagh</option><option value="saudi-white">Saudi — white ghutra</option></select><p>Click the bot to test interaction.</p></div><InteractionLab active={interaction} onTrigger={next=>triggerInteraction(next,true)}/></section></main>
    {guidance&&settings.enabled&&<div className={`floatingGuide priority-${guidance.priority}`} aria-live="polite"><div className="guideRobot"><AvatarScene state="idle" outfit={outfit} interaction="excited"/></div><div className="guideCallout"><strong>{guidance.title}</strong><span>{guidance.message}</span><button onClick={handleGuidanceAction}>{guidance.actionLabel}</button></div><div className="guidePointer">➜</div></div>}
    {overlayVisible&&<div className="overlay">{state==='game'?<MiniGame outfit={outfit} requestComplete={requestComplete} onContinue={finishGame} onExit={closeGame}/>:<div className="modal">{settings.enabled&&<div className="modalAvatar"><AvatarScene state={state} outfit={outfit} interaction={interaction} onPoke={settings.allowInteraction?()=>triggerInteraction('wave'):undefined}/></div>}<h2>{stateText[state].title}</h2><p>{message||stateText[state].body}</p>{state==='loading'&&<div className="progress"><div/></div>}{state==='loading'&&longWait&&settings.enableMiniGames&&<button className="primary" onClick={()=>setState('game')}>🎮 Play while waiting</button>}{(state==='error'||state==='offline')&&<div className="actions"><button className="primary" onClick={()=>simulate(5000)}>Retry</button>{settings.enableMiniGames&&<button onClick={()=>{setRequestComplete(false);setPendingOutcome('success');setState('game')}}>Keep playing</button>}</div>}{state==='success'&&<button className="primary" onClick={()=>{setRequestComplete(false);clearInteraction();setState('idle')}}>Continue</button>}</div>}</div>}
    {settingsOpen&&<ExperienceSettings settings={settings} onChange={setSettings} onClose={()=>setSettingsOpen(false)}/>} </div>
}
